[modem]
type = "quectel"
port = "/dev/ttyUSB2"
baud_rate = 115200
timeout = 1.0

[gnss_receiver]
type = "nmea_serial"
port = "/dev/serial0"
baud_rate = 9600
timeout = 1.0

[collector]
position_threshold = 15
max_idle_time = 200
max_wait_for_first_fix = 300
wait_log_interval = 5
keep_alive_host = "8.8.8.8"
keep_alive_port = 53
keep_alive_interval_s = 4.0

[uploader]
upload_dir = "/home/admin/Logger/upload_queue"
upload_user = "tim"
upload_host = "141.82.3.41"
upload_port = 2000
remote_dir = "/home/tim/5g-measurement-software/uploads/"
debug_upload = true

[logging]
level = "INFO"
log_file = "5g-measurement.log"
max_bytes = 5_000_000
backup_count = 3

[system]
running_on_pi = false
shutdown_gpio = 17
network_interfaces = ["wlan0", "wwan0"]